// Do NOT make any changes to this file!

const uuidAPIKey = require('uuid-apikey');

// converts a uuid to a string resembling an API Key
//  id must be valid uuid
function getKey(id) {
  return uuidAPIKey.toAPIKey(id, { 'noDashes': true });
}

// converts an API Key string to a uuid
//  key must be one that was generated by uuid-apikey
function getId(key) {
  return uuidAPIKey.toUUID(key);
}

module.exports = { getKey, getId }
